services:
  react:
    container_name: react-prod
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
