name: Deploy to VPS on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SSH to VPS and pull + build docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/tahtafm/apps/portofolio
            echo "==> Set git safe directory"
            git config --global --add safe.directory /home/tahtafm/apps/portofolio

            echo "==> Fetching and resetting to latest origin/main"
            git fetch origin
            git reset --hard origin/main
            docker compose up --build -d
